# 02 - Preprocessamento e modelo

Objetivo: carregar reviews, tokenizar/vetorizar os textos e treinar um modelo neural para classificar sentimento.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "notebooks":
    PROJECT_ROOT = PROJECT_ROOT.parent

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DATA_DIR = PROJECT_ROOT / "data" / "raw" / "aclImdb"
MODELS_DIR = PROJECT_ROOT / "models"
MODELS_DIR.mkdir(exist_ok=True)

print("Projeto:", PROJECT_ROOT)
print("Dados:", DATA_DIR)

Projeto: C:\Users\Carlos henrique\Documents\deeplearning
Dados: C:\Users\Carlos henrique\Documents\deeplearning\data\raw\aclImdb

In [2]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

from src.imdb_data import load_reviews

tf.keras.utils.set_random_seed(42)
print("TensorFlow:", tf.__version__)


def clean_text_array(values):
    cleaned = []
    for text in values:
        text = text.replace("<br />", " ")
        text = text.encode("ascii", "ignore").decode("ascii")
        cleaned.append(text)
    return np.array(cleaned, dtype=object)

TensorFlow: 2.21.0

## Carregamento e divisao

In [3]:
df = load_reviews(DATA_DIR)
train_df = df[df["split"] == "train"].sample(frac=1, random_state=42).reset_index(drop=True)
test_df = df[df["split"] == "test"].sample(frac=1, random_state=42).reset_index(drop=True)

x_train = clean_text_array(train_df["review"].to_numpy())
y_train = train_df["target"].to_numpy()
x_test = clean_text_array(test_df["review"].to_numpy())
y_test = test_df["target"].to_numpy()

print("Treino:", x_train.shape, y_train.shape)
print("Teste:", x_test.shape, y_test.shape)
train_df[["split", "label", "target", "review"]].head()

Treino: (25000,) (25000,)
Teste: (25000,) (25000,)

   split label  target                                             review
0  train   neg       0  Silent Night, Deadly Night 5 is the very last ...
1  train   pos       1  The idea ia a very short film with a lot of in...
2  train   neg       0  For me, this movie just seemed to fall on its ...
3  train   pos       1  Was this based on a comic-book? A video-game? ...
4  train   pos       1  Caution: May contain spoilers...<br /><br />I'...

## Vetorizacao dos textos

In [4]:
MAX_TOKENS = 20000
SEQUENCE_LENGTH = 250

vectorizer = layers.TextVectorization(
    max_tokens=MAX_TOKENS,
    output_mode="int",
    output_sequence_length=SEQUENCE_LENGTH,
    standardize="lower_and_strip_punctuation",
)
vectorizer.adapt(x_train)

vocab = vectorizer.get_vocabulary()
print("Tamanho do vocabulario:", len(vocab))
print("Primeiros tokens:", vocab[:20])

Tamanho do vocabulario: 20000
Primeiros tokens: ['', '[UNK]', np.str_('the'), np.str_('and'), np.str_('a'), np.str_('of'), np.str_('to'), np.str_('is'), np.str_('in'), np.str_('it'), np.str_('i'), np.str_('this'), np.str_('that'), np.str_('was'), np.str_('as'), np.str_('for'), np.str_('with'), np.str_('movie'), np.str_('but'), np.str_('film')]

In [5]:
example_text = x_train[0]
print(example_text[:500])
print(vectorizer([example_text]).numpy()[0][:40])

Silent Night, Deadly Night 5 is the very last of the series, and like part 4, it's unrelated to the first three except by title and the fact that it's a Christmas-themed horror flick.  Except to the oblivious, there's some obvious things going on here...Mickey Rooney plays a toymaker named Joe Petto and his creepy son's name is Pino. Ring a bell, anyone? Now, a little boy named Derek heard a knock at the door one evening, and opened it to find a present on the doorstep for him. Even though it sa
[1252  310 2440  310  664    7    2   52  227    5    2  200    3   38
  170  653   29 5676    6    2   85  291  546   32  416    3    2  186
   12   29    4    1  196  503  546    6    2 7838  216   46]

## Modelo neural

In [6]:
inputs = keras.Input(shape=(1,), dtype=tf.string, name="review")
x = vectorizer(inputs)
x = layers.Embedding(input_dim=len(vocab), output_dim=64, mask_zero=True, name="embedding")(x)
x = layers.Bidirectional(layers.LSTM(32), name="bilstm")(x)
x = layers.Dropout(0.4)(x)
x = layers.Dense(32, activation="relu")(x)
x = layers.Dropout(0.3)(x)
outputs = layers.Dense(1, activation="sigmoid", name="sentiment")(x)

model = keras.Model(inputs, outputs, name="imdb_sentiment_bilstm")
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=["accuracy"],
)
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "imdb_sentiment_bilstm"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ review (InputLayer) │ (None, 1)         │          0 │ -                 │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ text_vectorization  │ (None, 250)       │          0 │ review[0][0]      │
│ (TextVectorization) │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ embedding           │ (None, 250, 64)   │  1,280,000 │ text_vectorizati… │
│ (Embedding)         │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal           │ (None, 250)       │          0 │ text_vectorizati… │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ bilstm              │ (None, 64)        │     24,832 │ embedding[0][0],  │
│ (Bidirectional)     │                   │            │ not_equal[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout (Dropout)   │ (None, 64)        │          0 │ bilstm[0][0]      │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense (Dense)       │ (None, 32)        │      2,080 │ dropout[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_1 (Dropout) │ (None, 32)        │          0 │ dense[0][0]       │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ sentiment (Dense)   │ (None, 1)         │         33 │ dropout_1[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,306,945 (4.99 MB)

 Trainable params: 1,306,945 (4.99 MB)

 Non-trainable params: 0 (0.00 B)

## Treinamento

In [7]:
callbacks = [
    keras.callbacks.EarlyStopping(monitor="val_loss", patience=1, restore_best_weights=True),
]

history = model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    epochs=3,
    batch_size=256,
    callbacks=callbacks,
    verbose=1,
)

Epoch 1/3

 1/79 ━━━━━━━━━━━━━━━━━━━━ 4:56 4s/step - accuracy: 0.4766 - loss: 0.6936

 2/79 ━━━━━━━━━━━━━━━━━━━━ 34s 454ms/step - accuracy: 0.4775 - loss: 0.6935

 3/79 ━━━━━━━━━━━━━━━━━━━━ 34s 451ms/step - accuracy: 0.4798 - loss: 0.6935

 4/79 ━━━━━━━━━━━━━━━━━━━━ 33s 447ms/step - accuracy: 0.4851 - loss: 0.6934

 5/79 ━━━━━━━━━━━━━━━━━━━━ 33s 449ms/step - accuracy: 0.4875 - loss: 0.6934

 6/79 ━━━━━━━━━━━━━━━━━━━━ 32s 450ms/step - accuracy: 0.4902 - loss: 0.6933

 7/79 ━━━━━━━━━━━━━━━━━━━━ 32s 450ms/step - accuracy: 0.4922 - loss: 0.6933

 8/79 ━━━━━━━━━━━━━━━━━━━━ 31s 450ms/step - accuracy: 0.4934 - loss: 0.6933

 9/79 ━━━━━━━━━━━━━━━━━━━━ 31s 453ms/step - accuracy: 0.4956 - loss: 0.6932

10/79 ━━━━━━━━━━━━━━━━━━━━ 31s 454ms/step - accuracy: 0.4972 - loss: 0.6932

11/79 ━━━━━━━━━━━━━━━━━━━━ 30s 454ms/step - accuracy: 0.4985 - loss: 0.6932

12/79 ━━━━━━━━━━━━━━━━━━━━ 30s 454ms/step - accuracy: 0.4994 - loss: 0.6932

13/79 ━━━━━━━━━━━━━━━━━━━━ 29s 453ms/step - accuracy: 0.5000 - loss: 0.6931

14/79 ━━━━━━━━━━━━━━━━━━━━ 29s 456ms/step - accuracy: 0.5004 - loss: 0.6931

15/79 ━━━━━━━━━━━━━━━━━━━━ 29s 458ms/step - accuracy: 0.5007 - loss: 0.6931

16/79 ━━━━━━━━━━━━━━━━━━━━ 29s 462ms/step - accuracy: 0.5011 - loss: 0.6931

17/79 ━━━━━━━━━━━━━━━━━━━━ 28s 463ms/step - accuracy: 0.5014 - loss: 0.6931

18/79 ━━━━━━━━━━━━━━━━━━━━ 28s 466ms/step - accuracy: 0.5016 - loss: 0.6931

19/79 ━━━━━━━━━━━━━━━━━━━━ 28s 469ms/step - accuracy: 0.5022 - loss: 0.6930

20/79 ━━━━━━━━━━━━━━━━━━━━ 27s 470ms/step - accuracy: 0.5027 - loss: 0.6930

21/79 ━━━━━━━━━━━━━━━━━━━━ 27s 471ms/step - accuracy: 0.5035 - loss: 0.6930

22/79 ━━━━━━━━━━━━━━━━━━━━ 26s 471ms/step - accuracy: 0.5042 - loss: 0.6930

23/79 ━━━━━━━━━━━━━━━━━━━━ 26s 472ms/step - accuracy: 0.5049 - loss: 0.6930

24/79 ━━━━━━━━━━━━━━━━━━━━ 26s 474ms/step - accuracy: 0.5057 - loss: 0.6929

25/79 ━━━━━━━━━━━━━━━━━━━━ 25s 475ms/step - accuracy: 0.5065 - loss: 0.6929

26/79 ━━━━━━━━━━━━━━━━━━━━ 25s 476ms/step - accuracy: 0.5074 - loss: 0.6929

27/79 ━━━━━━━━━━━━━━━━━━━━ 24s 477ms/step - accuracy: 0.5084 - loss: 0.6928

28/79 ━━━━━━━━━━━━━━━━━━━━ 24s 478ms/step - accuracy: 0.5092 - loss: 0.6928

29/79 ━━━━━━━━━━━━━━━━━━━━ 23s 478ms/step - accuracy: 0.5101 - loss: 0.6928

30/79 ━━━━━━━━━━━━━━━━━━━━ 23s 478ms/step - accuracy: 0.5110 - loss: 0.6927

31/79 ━━━━━━━━━━━━━━━━━━━━ 22s 479ms/step - accuracy: 0.5120 - loss: 0.6927

32/79 ━━━━━━━━━━━━━━━━━━━━ 22s 481ms/step - accuracy: 0.5129 - loss: 0.6926

33/79 ━━━━━━━━━━━━━━━━━━━━ 22s 481ms/step - accuracy: 0.5139 - loss: 0.6926

34/79 ━━━━━━━━━━━━━━━━━━━━ 21s 482ms/step - accuracy: 0.5148 - loss: 0.6925

35/79 ━━━━━━━━━━━━━━━━━━━━ 21s 483ms/step - accuracy: 0.5159 - loss: 0.6925

36/79 ━━━━━━━━━━━━━━━━━━━━ 20s 484ms/step - accuracy: 0.5169 - loss: 0.6924

37/79 ━━━━━━━━━━━━━━━━━━━━ 20s 484ms/step - accuracy: 0.5179 - loss: 0.6924

38/79 ━━━━━━━━━━━━━━━━━━━━ 19s 484ms/step - accuracy: 0.5190 - loss: 0.6923

39/79 ━━━━━━━━━━━━━━━━━━━━ 19s 484ms/step - accuracy: 0.5201 - loss: 0.6922

40/79 ━━━━━━━━━━━━━━━━━━━━ 18s 485ms/step - accuracy: 0.5212 - loss: 0.6921

41/79 ━━━━━━━━━━━━━━━━━━━━ 18s 486ms/step - accuracy: 0.5224 - loss: 0.6920

42/79 ━━━━━━━━━━━━━━━━━━━━ 18s 487ms/step - accuracy: 0.5236 - loss: 0.6919

43/79 ━━━━━━━━━━━━━━━━━━━━ 17s 488ms/step - accuracy: 0.5248 - loss: 0.6917

44/79 ━━━━━━━━━━━━━━━━━━━━ 17s 488ms/step - accuracy: 0.5261 - loss: 0.6916

45/79 ━━━━━━━━━━━━━━━━━━━━ 16s 488ms/step - accuracy: 0.5273 - loss: 0.6914

46/79 ━━━━━━━━━━━━━━━━━━━━ 16s 489ms/step - accuracy: 0.5286 - loss: 0.6911

47/79 ━━━━━━━━━━━━━━━━━━━━ 15s 488ms/step - accuracy: 0.5299 - loss: 0.6908

48/79 ━━━━━━━━━━━━━━━━━━━━ 15s 489ms/step - accuracy: 0.5313 - loss: 0.6905

49/79 ━━━━━━━━━━━━━━━━━━━━ 14s 489ms/step - accuracy: 0.5326 - loss: 0.6901

50/79 ━━━━━━━━━━━━━━━━━━━━ 14s 490ms/step - accuracy: 0.5339 - loss: 0.6897

51/79 ━━━━━━━━━━━━━━━━━━━━ 13s 490ms/step - accuracy: 0.5352 - loss: 0.6892

52/79 ━━━━━━━━━━━━━━━━━━━━ 13s 490ms/step - accuracy: 0.5366 - loss: 0.6887

53/79 ━━━━━━━━━━━━━━━━━━━━ 12s 491ms/step - accuracy: 0.5379 - loss: 0.6881

54/79 ━━━━━━━━━━━━━━━━━━━━ 12s 491ms/step - accuracy: 0.5393 - loss: 0.6875

55/79 ━━━━━━━━━━━━━━━━━━━━ 11s 492ms/step - accuracy: 0.5406 - loss: 0.6869

56/79 ━━━━━━━━━━━━━━━━━━━━ 11s 492ms/step - accuracy: 0.5420 - loss: 0.6863

57/79 ━━━━━━━━━━━━━━━━━━━━ 10s 493ms/step - accuracy: 0.5433 - loss: 0.6856

58/79 ━━━━━━━━━━━━━━━━━━━━ 10s 493ms/step - accuracy: 0.5447 - loss: 0.6849

59/79 ━━━━━━━━━━━━━━━━━━━━ 9s 494ms/step - accuracy: 0.5460 - loss: 0.6842

60/79 ━━━━━━━━━━━━━━━━━━━━ 9s 494ms/step - accuracy: 0.5473 - loss: 0.6835

61/79 ━━━━━━━━━━━━━━━━━━━━ 8s 495ms/step - accuracy: 0.5486 - loss: 0.6827

62/79 ━━━━━━━━━━━━━━━━━━━━ 8s 495ms/step - accuracy: 0.5499 - loss: 0.6819

63/79 ━━━━━━━━━━━━━━━━━━━━ 7s 495ms/step - accuracy: 0.5512 - loss: 0.6811

64/79 ━━━━━━━━━━━━━━━━━━━━ 7s 495ms/step - accuracy: 0.5526 - loss: 0.6803

65/79 ━━━━━━━━━━━━━━━━━━━━ 6s 495ms/step - accuracy: 0.5539 - loss: 0.6794

66/79 ━━━━━━━━━━━━━━━━━━━━ 6s 496ms/step - accuracy: 0.5552 - loss: 0.6786

67/79 ━━━━━━━━━━━━━━━━━━━━ 5s 496ms/step - accuracy: 0.5565 - loss: 0.6777

68/79 ━━━━━━━━━━━━━━━━━━━━ 5s 497ms/step - accuracy: 0.5578 - loss: 0.6768

69/79 ━━━━━━━━━━━━━━━━━━━━ 4s 497ms/step - accuracy: 0.5590 - loss: 0.6759

70/79 ━━━━━━━━━━━━━━━━━━━━ 4s 498ms/step - accuracy: 0.5603 - loss: 0.6750

71/79 ━━━━━━━━━━━━━━━━━━━━ 3s 498ms/step - accuracy: 0.5616 - loss: 0.6741

72/79 ━━━━━━━━━━━━━━━━━━━━ 3s 499ms/step - accuracy: 0.5628 - loss: 0.6732

73/79 ━━━━━━━━━━━━━━━━━━━━ 2s 499ms/step - accuracy: 0.5641 - loss: 0.6723

74/79 ━━━━━━━━━━━━━━━━━━━━ 2s 499ms/step - accuracy: 0.5654 - loss: 0.6714

75/79 ━━━━━━━━━━━━━━━━━━━━ 1s 499ms/step - accuracy: 0.5666 - loss: 0.6704

76/79 ━━━━━━━━━━━━━━━━━━━━ 1s 500ms/step - accuracy: 0.5679 - loss: 0.6695

77/79 ━━━━━━━━━━━━━━━━━━━━ 1s 501ms/step - accuracy: 0.5691 - loss: 0.6685

78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 502ms/step - accuracy: 0.5703 - loss: 0.6676

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 496ms/step - accuracy: 0.5715 - loss: 0.6667

79/79 ━━━━━━━━━━━━━━━━━━━━ 44s 518ms/step - accuracy: 0.6658 - loss: 0.5938 - val_accuracy: 0.8518 - val_loss: 0.3804

Epoch 2/3

 1/79 ━━━━━━━━━━━━━━━━━━━━ 34s 447ms/step - accuracy: 0.8828 - loss: 0.3553

 2/79 ━━━━━━━━━━━━━━━━━━━━ 33s 437ms/step - accuracy: 0.8867 - loss: 0.3538

 3/79 ━━━━━━━━━━━━━━━━━━━━ 34s 455ms/step - accuracy: 0.8841 - loss: 0.3538

 4/79 ━━━━━━━━━━━━━━━━━━━━ 34s 462ms/step - accuracy: 0.8796 - loss: 0.3557

 5/79 ━━━━━━━━━━━━━━━━━━━━ 34s 466ms/step - accuracy: 0.8768 - loss: 0.3558

 6/79 ━━━━━━━━━━━━━━━━━━━━ 34s 468ms/step - accuracy: 0.8733 - loss: 0.3575

 7/79 ━━━━━━━━━━━━━━━━━━━━ 33s 469ms/step - accuracy: 0.8708 - loss: 0.3592

 8/79 ━━━━━━━━━━━━━━━━━━━━ 33s 466ms/step - accuracy: 0.8692 - loss: 0.3601

 9/79 ━━━━━━━━━━━━━━━━━━━━ 32s 466ms/step - accuracy: 0.8683 - loss: 0.3605

10/79 ━━━━━━━━━━━━━━━━━━━━ 32s 468ms/step - accuracy: 0.8674 - loss: 0.3608

11/79 ━━━━━━━━━━━━━━━━━━━━ 32s 472ms/step - accuracy: 0.8668 - loss: 0.3609

12/79 ━━━━━━━━━━━━━━━━━━━━ 31s 474ms/step - accuracy: 0.8665 - loss: 0.3606

13/79 ━━━━━━━━━━━━━━━━━━━━ 31s 475ms/step - accuracy: 0.8664 - loss: 0.3601

14/79 ━━━━━━━━━━━━━━━━━━━━ 31s 477ms/step - accuracy: 0.8662 - loss: 0.3597

15/79 ━━━━━━━━━━━━━━━━━━━━ 30s 481ms/step - accuracy: 0.8661 - loss: 0.3591

16/79 ━━━━━━━━━━━━━━━━━━━━ 30s 481ms/step - accuracy: 0.8660 - loss: 0.3587

17/79 ━━━━━━━━━━━━━━━━━━━━ 29s 481ms/step - accuracy: 0.8660 - loss: 0.3581

18/79 ━━━━━━━━━━━━━━━━━━━━ 29s 482ms/step - accuracy: 0.8660 - loss: 0.3575

19/79 ━━━━━━━━━━━━━━━━━━━━ 29s 484ms/step - accuracy: 0.8660 - loss: 0.3569

20/79 ━━━━━━━━━━━━━━━━━━━━ 28s 485ms/step - accuracy: 0.8661 - loss: 0.3563

21/79 ━━━━━━━━━━━━━━━━━━━━ 28s 485ms/step - accuracy: 0.8660 - loss: 0.3559

22/79 ━━━━━━━━━━━━━━━━━━━━ 27s 485ms/step - accuracy: 0.8659 - loss: 0.3555

23/79 ━━━━━━━━━━━━━━━━━━━━ 27s 485ms/step - accuracy: 0.8658 - loss: 0.3553

24/79 ━━━━━━━━━━━━━━━━━━━━ 26s 485ms/step - accuracy: 0.8657 - loss: 0.3550

25/79 ━━━━━━━━━━━━━━━━━━━━ 26s 486ms/step - accuracy: 0.8656 - loss: 0.3548

26/79 ━━━━━━━━━━━━━━━━━━━━ 25s 486ms/step - accuracy: 0.8656 - loss: 0.3544

27/79 ━━━━━━━━━━━━━━━━━━━━ 25s 487ms/step - accuracy: 0.8655 - loss: 0.3542

28/79 ━━━━━━━━━━━━━━━━━━━━ 24s 487ms/step - accuracy: 0.8655 - loss: 0.3539

29/79 ━━━━━━━━━━━━━━━━━━━━ 24s 487ms/step - accuracy: 0.8654 - loss: 0.3537

30/79 ━━━━━━━━━━━━━━━━━━━━ 23s 486ms/step - accuracy: 0.8654 - loss: 0.3535

31/79 ━━━━━━━━━━━━━━━━━━━━ 23s 486ms/step - accuracy: 0.8654 - loss: 0.3533

32/79 ━━━━━━━━━━━━━━━━━━━━ 22s 486ms/step - accuracy: 0.8654 - loss: 0.3530

33/79 ━━━━━━━━━━━━━━━━━━━━ 22s 486ms/step - accuracy: 0.8654 - loss: 0.3528

34/79 ━━━━━━━━━━━━━━━━━━━━ 21s 486ms/step - accuracy: 0.8654 - loss: 0.3525

35/79 ━━━━━━━━━━━━━━━━━━━━ 21s 486ms/step - accuracy: 0.8655 - loss: 0.3522

36/79 ━━━━━━━━━━━━━━━━━━━━ 20s 486ms/step - accuracy: 0.8655 - loss: 0.3519

37/79 ━━━━━━━━━━━━━━━━━━━━ 20s 486ms/step - accuracy: 0.8656 - loss: 0.3515

38/79 ━━━━━━━━━━━━━━━━━━━━ 19s 486ms/step - accuracy: 0.8657 - loss: 0.3511

39/79 ━━━━━━━━━━━━━━━━━━━━ 19s 485ms/step - accuracy: 0.8658 - loss: 0.3507

40/79 ━━━━━━━━━━━━━━━━━━━━ 18s 486ms/step - accuracy: 0.8659 - loss: 0.3503

41/79 ━━━━━━━━━━━━━━━━━━━━ 18s 486ms/step - accuracy: 0.8660 - loss: 0.3499

42/79 ━━━━━━━━━━━━━━━━━━━━ 18s 487ms/step - accuracy: 0.8661 - loss: 0.3494

43/79 ━━━━━━━━━━━━━━━━━━━━ 17s 488ms/step - accuracy: 0.8663 - loss: 0.3490

44/79 ━━━━━━━━━━━━━━━━━━━━ 17s 488ms/step - accuracy: 0.8664 - loss: 0.3484

45/79 ━━━━━━━━━━━━━━━━━━━━ 16s 488ms/step - accuracy: 0.8666 - loss: 0.3479

46/79 ━━━━━━━━━━━━━━━━━━━━ 16s 488ms/step - accuracy: 0.8668 - loss: 0.3473

47/79 ━━━━━━━━━━━━━━━━━━━━ 15s 488ms/step - accuracy: 0.8670 - loss: 0.3467

48/79 ━━━━━━━━━━━━━━━━━━━━ 15s 487ms/step - accuracy: 0.8672 - loss: 0.3461

49/79 ━━━━━━━━━━━━━━━━━━━━ 14s 487ms/step - accuracy: 0.8674 - loss: 0.3455

50/79 ━━━━━━━━━━━━━━━━━━━━ 14s 487ms/step - accuracy: 0.8677 - loss: 0.3449

51/79 ━━━━━━━━━━━━━━━━━━━━ 13s 487ms/step - accuracy: 0.8679 - loss: 0.3442

52/79 ━━━━━━━━━━━━━━━━━━━━ 13s 487ms/step - accuracy: 0.8681 - loss: 0.3436

53/79 ━━━━━━━━━━━━━━━━━━━━ 12s 487ms/step - accuracy: 0.8684 - loss: 0.3429

54/79 ━━━━━━━━━━━━━━━━━━━━ 12s 488ms/step - accuracy: 0.8686 - loss: 0.3423

55/79 ━━━━━━━━━━━━━━━━━━━━ 11s 488ms/step - accuracy: 0.8689 - loss: 0.3416

56/79 ━━━━━━━━━━━━━━━━━━━━ 11s 488ms/step - accuracy: 0.8691 - loss: 0.3410

57/79 ━━━━━━━━━━━━━━━━━━━━ 10s 488ms/step - accuracy: 0.8694 - loss: 0.3404

58/79 ━━━━━━━━━━━━━━━━━━━━ 10s 488ms/step - accuracy: 0.8696 - loss: 0.3397

59/79 ━━━━━━━━━━━━━━━━━━━━ 9s 488ms/step - accuracy: 0.8698 - loss: 0.3391

60/79 ━━━━━━━━━━━━━━━━━━━━ 9s 488ms/step - accuracy: 0.8701 - loss: 0.3385

61/79 ━━━━━━━━━━━━━━━━━━━━ 8s 488ms/step - accuracy: 0.8703 - loss: 0.3379

62/79 ━━━━━━━━━━━━━━━━━━━━ 8s 489ms/step - accuracy: 0.8705 - loss: 0.3373

63/79 ━━━━━━━━━━━━━━━━━━━━ 7s 489ms/step - accuracy: 0.8708 - loss: 0.3367

64/79 ━━━━━━━━━━━━━━━━━━━━ 7s 489ms/step - accuracy: 0.8710 - loss: 0.3361

65/79 ━━━━━━━━━━━━━━━━━━━━ 6s 488ms/step - accuracy: 0.8712 - loss: 0.3355

66/79 ━━━━━━━━━━━━━━━━━━━━ 6s 489ms/step - accuracy: 0.8715 - loss: 0.3349

67/79 ━━━━━━━━━━━━━━━━━━━━ 5s 489ms/step - accuracy: 0.8717 - loss: 0.3343

68/79 ━━━━━━━━━━━━━━━━━━━━ 5s 490ms/step - accuracy: 0.8719 - loss: 0.3337

69/79 ━━━━━━━━━━━━━━━━━━━━ 4s 490ms/step - accuracy: 0.8722 - loss: 0.3331

70/79 ━━━━━━━━━━━━━━━━━━━━ 4s 490ms/step - accuracy: 0.8724 - loss: 0.3326

71/79 ━━━━━━━━━━━━━━━━━━━━ 3s 490ms/step - accuracy: 0.8726 - loss: 0.3320

72/79 ━━━━━━━━━━━━━━━━━━━━ 3s 490ms/step - accuracy: 0.8728 - loss: 0.3315

73/79 ━━━━━━━━━━━━━━━━━━━━ 2s 490ms/step - accuracy: 0.8731 - loss: 0.3309

74/79 ━━━━━━━━━━━━━━━━━━━━ 2s 491ms/step - accuracy: 0.8733 - loss: 0.3304

75/79 ━━━━━━━━━━━━━━━━━━━━ 1s 492ms/step - accuracy: 0.8735 - loss: 0.3298

76/79 ━━━━━━━━━━━━━━━━━━━━ 1s 492ms/step - accuracy: 0.8737 - loss: 0.3293

77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 493ms/step - accuracy: 0.8739 - loss: 0.3288

78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 493ms/step - accuracy: 0.8741 - loss: 0.3282

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 488ms/step - accuracy: 0.8743 - loss: 0.3277

79/79 ━━━━━━━━━━━━━━━━━━━━ 40s 504ms/step - accuracy: 0.8907 - loss: 0.2871 - val_accuracy: 0.8718 - val_loss: 0.3161

Epoch 3/3

 1/79 ━━━━━━━━━━━━━━━━━━━━ 36s 467ms/step - accuracy: 0.9375 - loss: 0.1704

 2/79 ━━━━━━━━━━━━━━━━━━━━ 37s 481ms/step - accuracy: 0.9385 - loss: 0.1740

 3/79 ━━━━━━━━━━━━━━━━━━━━ 36s 485ms/step - accuracy: 0.9382 - loss: 0.1756

 4/79 ━━━━━━━━━━━━━━━━━━━━ 36s 485ms/step - accuracy: 0.9368 - loss: 0.1798

 5/79 ━━━━━━━━━━━━━━━━━━━━ 35s 483ms/step - accuracy: 0.9357 - loss: 0.1826

 6/79 ━━━━━━━━━━━━━━━━━━━━ 34s 478ms/step - accuracy: 0.9347 - loss: 0.1849

 7/79 ━━━━━━━━━━━━━━━━━━━━ 34s 477ms/step - accuracy: 0.9340 - loss: 0.1868

 8/79 ━━━━━━━━━━━━━━━━━━━━ 34s 479ms/step - accuracy: 0.9337 - loss: 0.1880

 9/79 ━━━━━━━━━━━━━━━━━━━━ 33s 480ms/step - accuracy: 0.9336 - loss: 0.1888

10/79 ━━━━━━━━━━━━━━━━━━━━ 33s 480ms/step - accuracy: 0.9334 - loss: 0.1897

11/79 ━━━━━━━━━━━━━━━━━━━━ 32s 479ms/step - accuracy: 0.9332 - loss: 0.1904

12/79 ━━━━━━━━━━━━━━━━━━━━ 31s 477ms/step - accuracy: 0.9330 - loss: 0.1909

13/79 ━━━━━━━━━━━━━━━━━━━━ 31s 477ms/step - accuracy: 0.9329 - loss: 0.1911

14/79 ━━━━━━━━━━━━━━━━━━━━ 31s 478ms/step - accuracy: 0.9327 - loss: 0.1913

15/79 ━━━━━━━━━━━━━━━━━━━━ 30s 479ms/step - accuracy: 0.9325 - loss: 0.1915

16/79 ━━━━━━━━━━━━━━━━━━━━ 30s 478ms/step - accuracy: 0.9322 - loss: 0.1920

17/79 ━━━━━━━━━━━━━━━━━━━━ 29s 478ms/step - accuracy: 0.9320 - loss: 0.1924

18/79 ━━━━━━━━━━━━━━━━━━━━ 29s 478ms/step - accuracy: 0.9319 - loss: 0.1926

19/79 ━━━━━━━━━━━━━━━━━━━━ 28s 478ms/step - accuracy: 0.9318 - loss: 0.1930

20/79 ━━━━━━━━━━━━━━━━━━━━ 28s 477ms/step - accuracy: 0.9318 - loss: 0.1932

21/79 ━━━━━━━━━━━━━━━━━━━━ 27s 476ms/step - accuracy: 0.9317 - loss: 0.1934

22/79 ━━━━━━━━━━━━━━━━━━━━ 27s 477ms/step - accuracy: 0.9317 - loss: 0.1936

23/79 ━━━━━━━━━━━━━━━━━━━━ 26s 477ms/step - accuracy: 0.9316 - loss: 0.1938

24/79 ━━━━━━━━━━━━━━━━━━━━ 26s 477ms/step - accuracy: 0.9315 - loss: 0.1940

25/79 ━━━━━━━━━━━━━━━━━━━━ 25s 478ms/step - accuracy: 0.9315 - loss: 0.1941

26/79 ━━━━━━━━━━━━━━━━━━━━ 25s 477ms/step - accuracy: 0.9315 - loss: 0.1941

27/79 ━━━━━━━━━━━━━━━━━━━━ 24s 477ms/step - accuracy: 0.9315 - loss: 0.1942

28/79 ━━━━━━━━━━━━━━━━━━━━ 24s 478ms/step - accuracy: 0.9315 - loss: 0.1943

29/79 ━━━━━━━━━━━━━━━━━━━━ 23s 478ms/step - accuracy: 0.9314 - loss: 0.1945

30/79 ━━━━━━━━━━━━━━━━━━━━ 23s 478ms/step - accuracy: 0.9314 - loss: 0.1947

31/79 ━━━━━━━━━━━━━━━━━━━━ 22s 479ms/step - accuracy: 0.9313 - loss: 0.1948

32/79 ━━━━━━━━━━━━━━━━━━━━ 22s 479ms/step - accuracy: 0.9313 - loss: 0.1949

33/79 ━━━━━━━━━━━━━━━━━━━━ 21s 478ms/step - accuracy: 0.9313 - loss: 0.1950

34/79 ━━━━━━━━━━━━━━━━━━━━ 21s 477ms/step - accuracy: 0.9313 - loss: 0.1950

35/79 ━━━━━━━━━━━━━━━━━━━━ 21s 477ms/step - accuracy: 0.9312 - loss: 0.1951

36/79 ━━━━━━━━━━━━━━━━━━━━ 20s 477ms/step - accuracy: 0.9312 - loss: 0.1951

37/79 ━━━━━━━━━━━━━━━━━━━━ 20s 478ms/step - accuracy: 0.9313 - loss: 0.1951

38/79 ━━━━━━━━━━━━━━━━━━━━ 19s 478ms/step - accuracy: 0.9313 - loss: 0.1950

39/79 ━━━━━━━━━━━━━━━━━━━━ 19s 478ms/step - accuracy: 0.9313 - loss: 0.1950

40/79 ━━━━━━━━━━━━━━━━━━━━ 18s 478ms/step - accuracy: 0.9314 - loss: 0.1949

41/79 ━━━━━━━━━━━━━━━━━━━━ 18s 477ms/step - accuracy: 0.9315 - loss: 0.1947

42/79 ━━━━━━━━━━━━━━━━━━━━ 17s 477ms/step - accuracy: 0.9316 - loss: 0.1946

43/79 ━━━━━━━━━━━━━━━━━━━━ 17s 477ms/step - accuracy: 0.9317 - loss: 0.1944

44/79 ━━━━━━━━━━━━━━━━━━━━ 16s 477ms/step - accuracy: 0.9318 - loss: 0.1942

45/79 ━━━━━━━━━━━━━━━━━━━━ 16s 477ms/step - accuracy: 0.9319 - loss: 0.1940

46/79 ━━━━━━━━━━━━━━━━━━━━ 15s 477ms/step - accuracy: 0.9320 - loss: 0.1937

47/79 ━━━━━━━━━━━━━━━━━━━━ 15s 477ms/step - accuracy: 0.9322 - loss: 0.1935

48/79 ━━━━━━━━━━━━━━━━━━━━ 14s 477ms/step - accuracy: 0.9323 - loss: 0.1932

49/79 ━━━━━━━━━━━━━━━━━━━━ 14s 477ms/step - accuracy: 0.9324 - loss: 0.1929

50/79 ━━━━━━━━━━━━━━━━━━━━ 13s 478ms/step - accuracy: 0.9325 - loss: 0.1927

51/79 ━━━━━━━━━━━━━━━━━━━━ 13s 478ms/step - accuracy: 0.9327 - loss: 0.1924

52/79 ━━━━━━━━━━━━━━━━━━━━ 12s 478ms/step - accuracy: 0.9328 - loss: 0.1922

53/79 ━━━━━━━━━━━━━━━━━━━━ 12s 478ms/step - accuracy: 0.9329 - loss: 0.1919

54/79 ━━━━━━━━━━━━━━━━━━━━ 11s 478ms/step - accuracy: 0.9331 - loss: 0.1916

55/79 ━━━━━━━━━━━━━━━━━━━━ 11s 478ms/step - accuracy: 0.9332 - loss: 0.1914

56/79 ━━━━━━━━━━━━━━━━━━━━ 10s 478ms/step - accuracy: 0.9333 - loss: 0.1911

57/79 ━━━━━━━━━━━━━━━━━━━━ 10s 478ms/step - accuracy: 0.9334 - loss: 0.1909

58/79 ━━━━━━━━━━━━━━━━━━━━ 10s 479ms/step - accuracy: 0.9336 - loss: 0.1906

59/79 ━━━━━━━━━━━━━━━━━━━━ 9s 479ms/step - accuracy: 0.9337 - loss: 0.1903

60/79 ━━━━━━━━━━━━━━━━━━━━ 9s 479ms/step - accuracy: 0.9338 - loss: 0.1900

61/79 ━━━━━━━━━━━━━━━━━━━━ 8s 478ms/step - accuracy: 0.9339 - loss: 0.1898

62/79 ━━━━━━━━━━━━━━━━━━━━ 8s 478ms/step - accuracy: 0.9341 - loss: 0.1895

63/79 ━━━━━━━━━━━━━━━━━━━━ 7s 478ms/step - accuracy: 0.9342 - loss: 0.1893

64/79 ━━━━━━━━━━━━━━━━━━━━ 7s 478ms/step - accuracy: 0.9343 - loss: 0.1890

65/79 ━━━━━━━━━━━━━━━━━━━━ 6s 478ms/step - accuracy: 0.9344 - loss: 0.1887

66/79 ━━━━━━━━━━━━━━━━━━━━ 6s 478ms/step - accuracy: 0.9346 - loss: 0.1884

67/79 ━━━━━━━━━━━━━━━━━━━━ 5s 478ms/step - accuracy: 0.9347 - loss: 0.1882

68/79 ━━━━━━━━━━━━━━━━━━━━ 5s 478ms/step - accuracy: 0.9348 - loss: 0.1879

69/79 ━━━━━━━━━━━━━━━━━━━━ 4s 478ms/step - accuracy: 0.9349 - loss: 0.1877

70/79 ━━━━━━━━━━━━━━━━━━━━ 4s 479ms/step - accuracy: 0.9350 - loss: 0.1874

71/79 ━━━━━━━━━━━━━━━━━━━━ 3s 479ms/step - accuracy: 0.9351 - loss: 0.1872

72/79 ━━━━━━━━━━━━━━━━━━━━ 3s 480ms/step - accuracy: 0.9352 - loss: 0.1870

73/79 ━━━━━━━━━━━━━━━━━━━━ 2s 481ms/step - accuracy: 0.9353 - loss: 0.1868

74/79 ━━━━━━━━━━━━━━━━━━━━ 2s 481ms/step - accuracy: 0.9354 - loss: 0.1866

75/79 ━━━━━━━━━━━━━━━━━━━━ 1s 482ms/step - accuracy: 0.9355 - loss: 0.1864

76/79 ━━━━━━━━━━━━━━━━━━━━ 1s 482ms/step - accuracy: 0.9356 - loss: 0.1862

77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 483ms/step - accuracy: 0.9356 - loss: 0.1860

78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 484ms/step - accuracy: 0.9357 - loss: 0.1858

79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 479ms/step - accuracy: 0.9358 - loss: 0.1856

79/79 ━━━━━━━━━━━━━━━━━━━━ 39s 495ms/step - accuracy: 0.9420 - loss: 0.1708 - val_accuracy: 0.8394 - val_loss: 0.4071

In [8]:
history_df = pd.DataFrame(history.history)
history_df

   accuracy      loss  val_accuracy  val_loss
0   0.66580  0.593783        0.8518  0.380405
1   0.89075  0.287110        0.8718  0.316051
2   0.94205  0.170846        0.8394  0.407071

## Avaliacao rapida e salvamento

In [9]:
test_loss, test_accuracy = model.evaluate(x_test, y_test, batch_size=256, verbose=0)
print(f"Loss teste: {test_loss:.4f}")
print(f"Accuracy teste: {test_accuracy:.4f}")

model_path = MODELS_DIR / "imdb_sentiment_model.keras"
history_path = MODELS_DIR / "training_history.csv"

model.save(model_path)
history_df.to_csv(history_path, index=False)

print("Modelo salvo em:", model_path)
print("Historico salvo em:", history_path)

Loss teste: 0.3614
Accuracy teste: 0.8477
Modelo salvo em: C:\Users\Carlos henrique\Documents\deeplearning\models\imdb_sentiment_model.keras
Historico salvo em: C:\Users\Carlos henrique\Documents\deeplearning\models\training_history.csv